name: Archive PR to Notion

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  archive-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Process PR commits and send to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: "25f0778f-fac8-802e-8444-c1a490714fd8"
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        shell: python
        run: |
          import os
          import requests
          import subprocess

          api_key = os.getenv('NOTION_API_KEY')
          db_id = os.getenv('NOTION_DATABASE_ID')
          repo_name = os.getenv('GITHUB_REPOSITORY')
          pr_number = os.getenv('PR_NUMBER')
          pr_title = os.getenv('PR_TITLE')
          pr_branch = os.getenv('PR_BRANCH')
          base_branch = os.getenv('BASE_BRANCH')

          headers = {
              "Authorization": f"Bearer {api_key}",
              "Content-Type": "application/json",
              "Notion-Version": "2022-06-28"
          }

          # PR의 커밋들 가져오기
          result = subprocess.run([
              'git', 'rev-list', 
              f'origin/{base_branch}..origin/{pr_branch}'
          ], capture_output=True, text=True)
          
          commit_shas = result.stdout.strip().split('\n')
          
          for sha in commit_shas:
              if not sha:
                  continue
                  
              # 각 커밋 정보를 개별적으로 가져오기
              commit_title = subprocess.run(['git', 'log', '-1', '--pretty=format:%s', sha], 
                                         capture_output=True, text=True).stdout
              commit_message_full = subprocess.run(['git', 'log', '-1', '--pretty=format:%B', sha], 
                                                 capture_output=True, text=True).stdout
              author_name = subprocess.run(['git', 'log', '-1', '--pretty=format:%an', sha], 
                                         capture_output=True, text=True).stdout
              commit_timestamp = subprocess.run(['git', 'log', '-1', '--pretty=format:%aI', sha], 
                                              capture_output=True, text=True).stdout

              # 1. 각 커밋마다 개별 페이지 생성
              page_data = {
                  "parent": {"database_id": db_id},
                  "properties": {
                      "Commit": {"title": [{"text": {"content": commit_title}}]},
                      "SHA": {"rich_text": [{"text": {"content": sha}}]},
                      "Project": {"select": {"name": repo_name}},
                      "Date": {"date": {"start": commit_timestamp}},
                      "PR-Num": {"number": int(pr_number)}
                  }
              }
              
              create_response = requests.post("https://api.notion.com/v1/pages", headers=headers, json=page_data)
              
              if create_response.status_code != 200:
                  print(f"Failed to create page for commit {sha[:7]}.")
                  print(create_response.text)
                  continue

              new_page_id = create_response.json()['id']
              print(f"Successfully created page for commit {sha[:7]}. Page ID: {new_page_id}")

              # 2. 생성된 페이지에 콘텐츠 (블록) 추가
              code_diff = subprocess.run(['git', 'show', sha], capture_output=True, text=True).stdout
              if len(code_diff) > 1990:
                  code_diff = code_diff[:1990] + "\n..."

              blocks_data = {
                  "children": [
                      {
                          "object": "block",
                          "type": "heading_2",
                          "heading_2": {"rich_text": [{"type": "text", "text": {"content": f"PR #{pr_number}: {pr_title}"}}]}
                      },
                      {
                          "object": "block",
                          "type": "paragraph",
                          "paragraph": {"rich_text": [{"type": "text", "text": {"content": f"Branch: {pr_branch} → {base_branch}"}}]}
                      },
                      {
                          "object": "block",
                          "type": "heading_2",
                          "heading_2": {"rich_text": [{"type": "text", "text": {"content": "Commit Message"}}]}
                      },
                      {
                          "object": "block",
                          "type": "paragraph",
                          "paragraph": {"rich_text": [{"type": "text", "text": {"content": commit_message_full}}]}
                      },
                      {
                          "object": "block",
                          "type": "heading_2",
                          "heading_2": {"rich_text": [{"type": "text", "text": {"content": "Code Diff"}}]}
                      },
                      {
                          "object": "block",
                          "type": "code",
                          "code": {
                              "rich_text": [{"type": "text", "text": {"content": code_diff}}],
                              "language": "diff"
                          }
                      }
                  ]
              }

              append_response = requests.patch(f"https://api.notion.com/v1/blocks/{new_page_id}/children", headers=headers, json=blocks_data)

              if append_response.status_code == 200:
                  print(f"Successfully appended content to page {new_page_id}.")
              else:
                  print(f"Failed to append content to page {new_page_id}.")
                  print(append_response.text)
